# Generated by Django 4.2.7 on 2023-11-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryicon',
            name='icon_image',
            field=models.FileField(upload_to='images/icons/'),
        ),
    ]
