# Generated by Django 4.2.7 on 2023-11-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0003_icon_category_image_1080_category_image_1920_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='service_images/')),
                ('image_500', models.ImageField(blank=True, upload_to='service_images_500/')),
                ('image_800', models.ImageField(blank=True, upload_to='service_images_800/')),
                ('image_1080', models.ImageField(blank=True, upload_to='service_images_1080/')),
                ('image_1920', models.ImageField(blank=True, upload_to='service_images_1920/')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='eyeapp.icon')),
            ],
        ),
    ]
