# Generated by Django 4.2.7 on 2023-11-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='service_nav',
            field=models.BooleanField(default=False),
        ),
    ]
