# Generated by Django 4.2.7 on 2023-11-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0005_service_featured_service_service_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='doctor_images/')),
                ('image_500', models.ImageField(blank=True, upload_to='doctor_images_500/')),
                ('image_800', models.ImageField(blank=True, upload_to='doctor_images_800/')),
                ('image_1018', models.ImageField(blank=True, upload_to='doctor_images_1018/')),
            ],
        ),
    ]
