# Generated by Django 4.2.7 on 2023-11-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0007_doctor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_description', models.TextField()),
                ('about_description', models.TextField()),
                ('experience', models.PositiveIntegerField()),
                ('expertise', models.CharField(max_length=255)),
                ('practice', models.CharField(max_length=255)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='eyeapp.doctor')),
            ],
        ),
    ]
