# Generated by Django 4.2.7 on 2023-11-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0008_doctordetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='expertise',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='practice',
            field=models.TextField(),
        ),
    ]
