# Generated by Django 4.2.7 on 2023-12-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0014_category_slug_categorydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
