# Generated by Django 4.2.7 on 2023-12-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0015_icon_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='equipment_images/')),
                ('image_500', models.ImageField(blank=True, upload_to='equipment_images_500/')),
                ('image_800', models.ImageField(blank=True, upload_to='equipment_images_800/')),
                ('image_1080', models.ImageField(blank=True, upload_to='equipment_images_1080/')),
                ('image_1920', models.ImageField(blank=True, upload_to='equipment_images_1920/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('image_500', models.ImageField(blank=True, upload_to='gallery_images_500/')),
                ('image_800', models.ImageField(blank=True, upload_to='gallery_images_800/')),
                ('image_1080', models.ImageField(blank=True, upload_to='gallery_images_1080/')),
                ('image_1920', models.ImageField(blank=True, upload_to='gallery_images_1920/')),
            ],
        ),
        migrations.CreateModel(
            name='Mizhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='mizhi_images/')),
                ('image_500', models.ImageField(blank=True, upload_to='mizhi_images_500/')),
                ('image_800', models.ImageField(blank=True, upload_to='mizhi_images_800/')),
                ('image_1080', models.ImageField(blank=True, upload_to='mizhi_images_1080/')),
                ('image_1920', models.ImageField(blank=True, upload_to='mizhi_images_1920/')),
            ],
        ),
    ]
