# Generated by Django 4.2.7 on 2023-12-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0016_equipment_gallery_mizhi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='about_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='expertise',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='main_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='practice',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeapp.blogcategory')),
            ],
        ),
    ]
