# Generated by Django 4.2.7 on 2023-12-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0018_blog_content_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('what_doctor', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Review_images/')),
            ],
        ),
    ]
