# Generated by Django 4.2.7 on 2024-02-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0019_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='management_team_images/')),
                ('image_500', models.ImageField(blank=True, upload_to='management_team_images_500/')),
                ('image_800', models.ImageField(blank=True, upload_to='management_team_images_800/')),
                ('image_1018', models.ImageField(blank=True, upload_to='management_team_images_1018/')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementTeamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_description', models.TextField(blank=True)),
                ('about_description', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('expertise', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('team_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='eyeapp.managementteam')),
            ],
        ),
    ]
